name: IAM Platform - Local
values:
  - key: base_url
    value: 'http://localhost:3000'
    enabled: true
  - key: access_token
    value: ''
    enabled: true
  - key: refresh_token
    value: ''
    enabled: true
  - key: org_id
    value: ''
    enabled: true
  - key: role_id
    value: ''
    enabled: true
  - key: permission_id
    value: ''
    enabled: true
  - key: membership_id
    value: ''
    enabled: true
  - key: session_id
    value: ''
    enabled: true
  - key: api_key_id
    value: ''
    enabled: true
